//! Per RFD 0028 §B.2-B.10: pure renderer from `Manifest` →
//! generated Cargo project (Cargo.toml + src/main.rs).
//!
//! `render` is a pure function: same `(manifest, pi_build_version)`
//! → byte-identical output (no clocks, no random, no env reads).
//! This is invariant B.13 #5 (codegen determinism).

use std::fmt::Write as _;

use sha2::{Digest, Sha256};

use crate::manifest::{Manifest, ThinkingLevel};

/// All three files produced by a `pi-build <agent.toml>` run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderedTree {
    pub cargo_toml: String,
    pub main_rs: String,
    pub pi_build_lock: String,
}

/// SHA-256 of the raw manifest bytes, hex-encoded. Deterministic.
pub fn manifest_sha256(raw: &str) -> String {
    let digest = Sha256::digest(raw.as_bytes());
    hex::encode(digest)
}

/// Render the full Cargo project tree from a manifest.
///
/// `pi_build_version` is the version of the pi-build binary doing
/// the codegen — bound to `env!("CARGO_PKG_VERSION")` at the CLI
/// entrypoint and used both as the pi-sdk caret-pin source and as
/// a header comment in every generated file.
pub fn render(
    manifest: &Manifest,
    raw_manifest: &str,
    pi_build_version: &str,
) -> RenderedTree {
    let sha = manifest_sha256(raw_manifest);
    RenderedTree {
        cargo_toml: render_cargo_toml(manifest, &sha, pi_build_version),
        main_rs: render_main_rs(manifest, &sha, pi_build_version),
        pi_build_lock: render_pi_build_lock(&sha, pi_build_version),
    }
}

// ── Cargo.toml ───────────────────────────────────────────────────

fn render_cargo_toml(m: &Manifest, sha: &str, pi_build_version: &str) -> String {
    // pi-sdk caret-pin: derived from pi-build's own version. v0.1.x
    // pi-build emits `pi-sdk = "0.1"`. Bump the major when pi-sdk
    // does, in lockstep.
    let pi_sdk_pin = caret_pin_for(pi_build_version);
    format!(
        r#"# CODE GENERATED by pi-build {pi_build_version} from agent.toml
# hash sha256:{sha}.
[package]
name    = "{name}"
version = "{version}"
edition = "2021"

[dependencies]
pi-sdk      = "{pi_sdk_pin}"
tokio       = {{ version = "1", features = ["macros", "rt", "sync"] }}
serde_json  = "1"

[profile.release]
lto             = "thin"
strip           = true
codegen-units   = 1
"#,
        name = m.agent.name,
        version = m.agent.version,
    )
}

/// Caret-pin for pi-sdk: strip patch + pre-release. `0.1.5` → `0.1`.
/// At 1.0+ we'd emit just the major (`1`) per the RFD 0027 §6
/// caret-pin policy, but for 0.x the API can break across minors,
/// so the pin is `MAJOR.MINOR`.
fn caret_pin_for(pi_build_version: &str) -> String {
    let v = semver::Version::parse(pi_build_version)
        .expect("pi_build_version must be valid SemVer (set by env!)");
    if v.major == 0 {
        format!("{}.{}", v.major, v.minor)
    } else {
        format!("{}", v.major)
    }
}

// ── pi-build.lock ────────────────────────────────────────────────

fn render_pi_build_lock(sha: &str, pi_build_version: &str) -> String {
    // Note: NO timestamp field per Commit C v1 — `generated_at_unix`
    // would break determinism. Reserved for Commit C v2 if `verify`
    // ever needs it.
    format!(
        r#"# Generated by pi-build. Do NOT edit.
pi_build_version = "{pi_build_version}"
manifest_sha256  = "{sha}"
"#
    )
}

// ── src/main.rs ──────────────────────────────────────────────────

fn render_main_rs(m: &Manifest, sha: &str, pi_build_version: &str) -> String {
    let auth_call = render_auth_call(m);
    let auth_check = render_auth_check(m);
    let tool_allowlist = render_tool_allowlist(&m.tools.allowlist);
    let provider_lit = quote_str(m.provider.name.as_kebab());
    let model_lit = quote_str(&m.provider.model);
    let thinking_lit = render_thinking_lit(m.provider.thinking);
    let system_prompt_lit = render_raw_string(&m.runtime.system_prompt);
    let mst = m.runtime.max_session_tokens;
    let mtipt = m.runtime.max_tool_invocations_per_turn;
    let mr = m.runtime.max_recursion;
    let agent_name = &m.agent.name;
    let agent_version = &m.agent.version;
    let provider_name = m.provider.name.as_kebab();
    let provider_model = &m.provider.model;
    let thinking_str = thinking_str(m.provider.thinking);

    // Single literal — kept as one fmt::write block so the
    // output is byte-stable across rustfmt edits to this source.
    let mut out = String::new();
    let _ = write!(
        &mut out,
        r#"// CODE GENERATED by pi-build {pi_build_version} from agent.toml
// hash sha256:{sha}.
// DO NOT EDIT. Regenerate via `pi-build agent.toml`.
//
// Agent:    {agent_name} v{agent_version}
// Provider: {provider_name}/{provider_model} (thinking={thinking_str})

use pi_sdk::{{
    create_agent_session, AgentEvent, AgentEventKind, AuthStorage, LocalProcessProvider,
    ModelRegistry, RuntimeConfig, SessionManager, Settings, ThinkingSetting,
    ToolRegistry,
}};
use std::sync::Arc;

#[tokio::main(flavor = "current_thread")]
async fn main() -> std::process::ExitCode {{
    let auth = match AuthStorage::{auth_call} {{
        Ok(a) => a,
        Err(_) => return std::process::ExitCode::from(2),
    }};
{auth_check}
    // Same registry passed to .tools() AND LocalProcessProvider::new
    // (B.13 invariant 1 — silent allowlist bypass otherwise).
    let mut tools = ToolRegistry::with_unsafe_extras();
    tools.keep_only(&[
{tool_allowlist}    ]);
    let sandbox = Arc::new(LocalProcessProvider::new(tools.clone()));

    // Explicit turbofish: the EventSender alias only constrains the
    // channel via Option<EventSender> in create_agent_session(), but
    // inference doesn't propagate backwards across the Option ctor
    // reliably (rustc emits E0282 on plain `unbounded_channel()`).
    let (event_tx, mut event_rx) = tokio::sync::mpsc::unbounded_channel::<AgentEvent>();
    let cfg = RuntimeConfig::builder()
        .session_manager(SessionManager::in_memory())
        .auth_storage(auth.clone())
        .model_registry(ModelRegistry::new(auth))
        .tools(tools)
        .settings(
            Settings::builder()
                .provider({provider_lit})
                .model({model_lit})
                .thinking({thinking_lit})
                .build(),
        )
        .system_prompt({system_prompt_lit})
        .with_sandbox_provider(sandbox)
        .with_max_session_tokens({mst}u64)
        .with_max_tool_invocations_per_turn({mtipt}usize)
        .with_max_recursion({mr}usize)
        .build()
        .expect("compile-time-validated config");

    // §Cross-cutting #4: stdout JSONL is `serde_json::to_string(&AgentEvent)`.
    // Use `writeln!` over a locked stdout handle so a broken-pipe error
    // (operator pipes through `head` etc.) ends the pump gracefully
    // rather than panicking on EPIPE inside println!.
    let jsonl = std::env::args().any(|a| a == "--jsonl");
    let pump = tokio::spawn(async move {{
        use std::io::Write as _;
        let stdout = std::io::stdout();
        while let Some(evt) = event_rx.recv().await {{
            let mut handle = stdout.lock();
            let r = if jsonl {{
                writeln!(handle, "{{}}", serde_json::to_string(&evt).unwrap())
            }} else if let AgentEventKind::AssistantTextDelta {{ text }} = &evt.kind {{
                write!(handle, "{{text}}")
            }} else {{
                Ok(())
            }};
            drop(handle);
            if r.is_err() {{ break; }}
            if matches!(evt.kind, AgentEventKind::TurnComplete) {{ break; }}
        }}
    }});

    // create_agent_session returns (AgentSessionRuntime, AgentSession);
    // _runtime is stylistic — AgentSession holds its own Arc<RuntimeConfig>.
    let (_runtime, session) = match create_agent_session(cfg, Some(event_tx)) {{
        Ok(rs) => rs,
        Err(_) => return std::process::ExitCode::from(1),
    }};
    let prompt = read_prompt_from_args_or_stdin();
    let exit = match session.prompt(prompt).await {{
        Ok(_) => 0,
        Err(e) => map_runtime_error_to_exit(e),
    }};
    let _ = pump.await;
    std::process::ExitCode::from(exit)
}}

fn read_prompt_from_args_or_stdin() -> String {{
    use std::io::{{IsTerminal, Read}};
    let args: Vec<String> = std::env::args().skip(1)
        .filter(|a| !a.starts_with("--"))
        .collect();
    if !args.is_empty() {{
        return args.join(" ");
    }}
    let stdin = std::io::stdin();
    if !stdin.is_terminal() {{
        let mut buf = String::new();
        if stdin.lock().read_to_string(&mut buf).is_ok() && !buf.trim().is_empty() {{
            return buf.trim().to_owned();
        }}
    }}
    eprintln!("usage: {agent_name} [--jsonl] <prompt> | echo <prompt> | {agent_name}");
    std::process::exit(64);
}}

fn map_runtime_error_to_exit(e: pi_sdk::RuntimeError) -> u8 {{
    use pi_sdk::RuntimeError::*;
    match e {{
        BudgetExhausted {{ .. }}        => 3,
        InvocationCapExceeded {{ .. }}  => 3,
        DepthExceeded {{ .. }}          => 1,
        EmptyTurn                       => 1,
        ToolPanicked {{ .. }}           => 1,
        ToolUseFinishWithoutCalls       => 1,
        _                               => 1,
    }}
}}
"#
    );
    out
}

// ── Substitution helpers (B.5-B.10) ──────────────────────────────

fn render_auth_check(m: &Manifest) -> String {
    // Per generated-agent code-review (post-Commit-B): pi-sdk's
    // `from_env_explicit` silently drops empty-string env vars
    // (`pi-ai/src/auth.rs:154` — `Ok(val) if !val.is_empty()` →
    // insert; otherwise skip). So `ANTHROPIC_API_KEY=""` produces
    // an empty AuthStorage that would later surface as a generic
    // RuntimeError::Provider — mapped to exit 1, NOT the exit 2
    // RFD §Cross-cutting #5 promises for missing auth.
    //
    // Bridge that gap by post-checking that the configured provider
    // actually has a credential after `from_env_explicit` returns.
    // Skip the check when `secrets.required` is empty (the agent
    // either doesn't need auth or sources it elsewhere).
    if m.secrets.required.is_empty() {
        return String::new();
    }
    let provider_lit = quote_str(m.provider.name.as_kebab());
    let env_list = m.secrets.required.join(", ");
    let env_list_lit = quote_str(&env_list);
    format!(
        "    if auth.get({provider_lit}).is_none() {{\n        \
            eprintln!(\"{{}}: missing credentials for provider {{}}; required env var(s) {{}} unset or empty\",\n            \
                env!(\"CARGO_PKG_NAME\"), {provider_lit}, {env_list_lit});\n        \
            return std::process::ExitCode::from(2);\n    \
        }}\n"
    )
}

fn render_auth_call(m: &Manifest) -> String {
    // B.6: empty allowlist → typed iter::empty (avoids E0282
    // "type annotations needed" on the from_env_explicit
    // generic <I, P, E>). Non-empty → array literal.
    let provider = m.provider.name.as_kebab();
    if m.secrets.required.is_empty() {
        "from_env_explicit(std::iter::empty::<(&str, &str)>())".into()
    } else {
        let pairs = m
            .secrets
            .required
            .iter()
            .map(|env| format!("({}, {})", quote_str(provider), quote_str(env)))
            .collect::<Vec<_>>()
            .join(", ");
        format!("from_env_explicit([{pairs}])")
    }
}

fn render_tool_allowlist(allow: &[String]) -> String {
    // Each entry on its own line, indented 8 spaces, terminated
    // with a comma. Trailing newline preserved.
    let mut out = String::new();
    for name in allow {
        let _ = writeln!(&mut out, "        {}.into(),", quote_str(name));
    }
    out
}

fn render_thinking_lit(t: ThinkingLevel) -> &'static str {
    // B.9: explicit literal mapping. NOT From<ThinkingLevel>
    // for ThinkingSetting — keeps the generated crate boilerplate-free.
    match t {
        ThinkingLevel::Off => "ThinkingSetting::Off",
        ThinkingLevel::Low => "ThinkingSetting::Low",
        ThinkingLevel::Medium => "ThinkingSetting::Medium",
        ThinkingLevel::High => "ThinkingSetting::High",
        ThinkingLevel::Xhigh => "ThinkingSetting::XHigh",
    }
}

fn thinking_str(t: ThinkingLevel) -> &'static str {
    // Display-only string for the comment header.
    match t {
        ThinkingLevel::Off => "off",
        ThinkingLevel::Low => "low",
        ThinkingLevel::Medium => "medium",
        ThinkingLevel::High => "high",
        ThinkingLevel::Xhigh => "xhigh",
    }
}

fn quote_str(s: &str) -> String {
    // Rust string-literal escaping. Handles "/"/'\'/'\n'/'\t'/control.
    // For multi-line system_prompt we use a raw-string variant
    // (render_raw_string) instead.
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str(r"\\"),
            '"' => out.push_str(r#"\""#),
            '\n' => out.push_str(r"\n"),
            '\r' => out.push_str(r"\r"),
            '\t' => out.push_str(r"\t"),
            c if c.is_control() => {
                let _ = write!(&mut out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn render_raw_string(s: &str) -> String {
    // For `system_prompt`, prefer a raw-string literal so newlines
    // + quotes survive without escaping. Pick the shortest hash
    // count that doesn't appear in the body.
    let mut hashes = 0usize;
    while s.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let pad = "#".repeat(hashes);
    format!("r{pad}\"{s}\"{pad}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::{
        AgentMeta, ProviderConfig, ProviderName, RuntimeConfig, SecretsConfig, ToolsConfig,
    };

    fn fixture_manifest() -> Manifest {
        Manifest {
            schema_version: 1,
            agent: AgentMeta {
                name: "dice-oracle".into(),
                description: "roll dice".into(),
                version: "0.1.0".into(),
            },
            provider: ProviderConfig {
                name: ProviderName::Anthropic,
                model: "claude-haiku-4-5-20251001".into(),
                thinking: ThinkingLevel::Medium,
            },
            secrets: SecretsConfig {
                required: vec!["ANTHROPIC_API_KEY".into()],
            },
            tools: ToolsConfig {
                allowlist: vec!["read".into(), "grep".into(), "bash".into()],
                disallow_unsafe: false,
            },
            runtime: RuntimeConfig {
                system_prompt: "Roll a d20.".into(),
                max_session_tokens: 200_000,
                max_tool_invocations_per_turn: 50,
                max_recursion: 4,
            },
        }
    }

    #[test]
    fn render_is_pure_deterministic() {
        let m = fixture_manifest();
        let raw = "schema_version = 1\n";
        let a = render(&m, raw, "0.1.0");
        let b = render(&m, raw, "0.1.0");
        assert_eq!(a, b, "render must be a pure function");
    }

    #[test]
    fn auth_call_empty_uses_iter_empty() {
        let mut m = fixture_manifest();
        m.secrets.required.clear();
        let s = render_auth_call(&m);
        assert_eq!(s, "from_env_explicit(std::iter::empty::<(&str, &str)>())");
    }

    #[test]
    fn auth_call_non_empty_uses_array_literal() {
        let m = fixture_manifest();
        let s = render_auth_call(&m);
        assert_eq!(s, r#"from_env_explicit([("anthropic", "ANTHROPIC_API_KEY")])"#);
    }

    #[test]
    fn caret_pin_for_zero_x_keeps_minor() {
        assert_eq!(caret_pin_for("0.1.5"), "0.1");
        assert_eq!(caret_pin_for("0.2.0"), "0.2");
    }

    #[test]
    fn caret_pin_for_one_plus_drops_minor() {
        assert_eq!(caret_pin_for("1.0.0"), "1");
        assert_eq!(caret_pin_for("2.5.7"), "2");
    }

    #[test]
    fn quote_str_escapes_special_chars() {
        assert_eq!(quote_str("hello"), r#""hello""#);
        assert_eq!(quote_str("with \"quotes\""), r#""with \"quotes\"""#);
        assert_eq!(quote_str("with\nnewline"), r#""with\nnewline""#);
        assert_eq!(quote_str("path\\sep"), r#""path\\sep""#);
    }

    #[test]
    fn render_raw_string_picks_minimal_hashes() {
        // No quotes → no hashes needed.
        assert_eq!(render_raw_string("hello"), r##"r"hello""##);
        // Body contains `"#` — need ≥ 2 hashes to avoid premature termination
        // at the close. (Build the body via concatenation to keep this test
        // source itself at 0 hashes.)
        let body = format!("contains {}{}", '"', '#');
        let out = render_raw_string(&body);
        // Hash count on both sides must match and be ≥ 2.
        let prefix_hashes = out.bytes().skip(1).take_while(|&b| b == b'#').count();
        let suffix_hashes = out.bytes().rev().take_while(|&b| b == b'#').count();
        assert_eq!(prefix_hashes, suffix_hashes, "hash counts must match");
        assert!(prefix_hashes >= 2, "got {prefix_hashes} hashes; need ≥ 2 for `\"#` body");
        // And the body MUST appear verbatim between the delimiters.
        let inner = &out[1 + prefix_hashes + 1 .. out.len() - 1 - suffix_hashes];
        assert_eq!(inner, body);
    }

    #[test]
    fn cargo_toml_contains_pi_sdk_caret_pin() {
        let m = fixture_manifest();
        let raw = "schema_version = 1\n";
        let r = render(&m, raw, "0.1.0");
        assert!(r.cargo_toml.contains(r#"pi-sdk      = "0.1""#), "{}", r.cargo_toml);
        assert!(r.cargo_toml.contains(r#"name    = "dice-oracle""#));
        assert!(r.cargo_toml.contains(r#"version = "0.1.0""#));
        assert!(r.cargo_toml.contains(r#"features = ["macros", "rt", "sync"]"#));
    }

    #[test]
    fn main_rs_contains_required_substrings() {
        let m = fixture_manifest();
        let raw = "schema_version = 1\n";
        let r = render(&m, raw, "0.1.0");

        // §Cross-cutting #9 invariant.
        assert!(
            r.main_rs.contains(r#"#[tokio::main(flavor = "current_thread")]"#),
            "main.rs must declare current_thread runtime"
        );
        // B.13 #1: same registry to .tools and sandbox.
        assert!(r.main_rs.contains(".tools(tools)"));
        assert!(r.main_rs.contains("LocalProcessProvider::new(tools.clone())"));
        // B.10 lowering: usize suffix.
        assert!(r.main_rs.contains("with_max_tool_invocations_per_turn(50usize)"));
        assert!(r.main_rs.contains("with_max_recursion(4usize)"));
        assert!(r.main_rs.contains("with_max_session_tokens(200000u64)"));
        // §Cross-cutting #4: serde_json on AgentEvent.
        assert!(r.main_rs.contains("serde_json::to_string(&evt).unwrap()"));
        // B.6 lowering — anthropic + ANTHROPIC_API_KEY pair literal.
        assert!(r.main_rs.contains(
            r#"from_env_explicit([("anthropic", "ANTHROPIC_API_KEY")])"#
        ));
        // B.9 lowering — Medium → ThinkingSetting::Medium.
        assert!(r.main_rs.contains(".thinking(ThinkingSetting::Medium)"));
    }

    #[test]
    fn pi_build_lock_records_version_and_sha() {
        let m = fixture_manifest();
        let raw = "schema_version = 1\nfoo = 1\n";
        let r = render(&m, raw, "0.1.0");
        let sha = manifest_sha256(raw);
        assert!(r.pi_build_lock.contains(&format!("manifest_sha256  = \"{sha}\"")));
        assert!(r.pi_build_lock.contains(r#"pi_build_version = "0.1.0""#));
        // No timestamp — would break determinism per §Cross-cutting #2.
        assert!(!r.pi_build_lock.contains("generated_at_unix"));
    }

    #[test]
    fn empty_secrets_renders_iter_empty_in_main_rs() {
        let mut m = fixture_manifest();
        m.secrets.required.clear();
        let r = render(&m, "schema_version = 1\n", "0.1.0");
        assert!(
            r.main_rs.contains("from_env_explicit(std::iter::empty::<(&str, &str)>())"),
            "empty secrets must render as typed iter::empty (B.13 invariant 8)"
        );
        // And NOT as the bare empty array which would fail to type-infer.
        assert!(!r.main_rs.contains("from_env_explicit([])"));
        // No auth.get check when there's no required secret to check.
        assert!(!r.main_rs.contains("auth.get("));
    }

    #[test]
    fn non_empty_secrets_renders_post_check_for_exit_2() {
        // Per generated-agent code-review post-Commit-B finding:
        // empty-string env vars are silently dropped by pi-sdk's
        // `from_env_explicit`, so the codegen MUST post-check that
        // the configured provider got a credential — otherwise the
        // RFD §Cross-cutting #5 exit-2 contract is unreachable.
        let m = fixture_manifest();
        let r = render(&m, "schema_version = 1\n", "0.1.0");
        assert!(
            r.main_rs.contains(r#"if auth.get("anthropic").is_none()"#),
            "main.rs must post-check auth presence; got:\n{}",
            r.main_rs
        );
        assert!(
            r.main_rs.contains("ExitCode::from(2)"),
            "the auth-check branch must exit 2 per §Cross-cutting #5"
        );
        // Error message names the env var so the operator can fix it.
        assert!(
            r.main_rs.contains("ANTHROPIC_API_KEY"),
            "error message must name the missing env var"
        );
    }
}
